# Generated by Django 2.2.1 on 2019-06-07 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='comment_contents',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_date',
            new_name='comment_date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='text',
        ),
    ]
